---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecom-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: os
  template:
    metadata:
      name: os-temp
      labels:
        app: os
    spec:
      containers:
        - name: os-cont1
          image: nginx:1.27
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cm-os
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: os-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: os-secret
                  key: DB_PASSWORD


