---
apiVersion: v1
kind: Secret
metadata:
  name: os-secret
  namespace: ecom-dev
type: Opaque
data:
  DB_HOST: bXlzcWwtc2VydmljZQ==
  DB_PORT: MzMwNg==
  DB_USERNAME: b3JkZXJfdXNlcg==
  DB_PASSWORD: T3JkZXJAMTIz
